version: "3.7"
services:
  db:
    image: "mysql"
    container_name: strengthscribe_db
    ports:
     - "3306:3306"
    environment:
       - MYSQL_ROOT_PASSWORD=admin
       - MYSQL_PASSWORD=admin
       - MYSQL_USER=admin
       - MYSQL_DATABASE=strengthscribe_db